{% set name = "opentelemetry-instrumentation-transformers" %}
{% set version = "0.51.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_transformers-{{ version }}.tar.gz
  sha256: d173fdd1538801c27aec111009eaebe11b81454bcc1fb45adc1e79dd51b48661

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-sdk >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.4.13,<0.5.0
  run_constrained:
    - transformers >=4.51.3

test:
  imports:
    - opentelemetry.instrumentation.transformers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - transformers

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry transformers instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
